version: "3.7"
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban_docker
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/home/docker/fail2ban/data:/data"
      - "/var/log/auth.log:/var/log/auth.log:ro"
      - "/home/docker/nginx-proxy-manager/data/logs/:/log/npm/:ro"
    restart: always
    environment:
      - TZ=${TZ}
      - F2B_LOG_TARGET=${FAIL2BAN_LOG_TARGET}
      - F2B_LOG_LEVEL=${FAIL2BAN_LOG_LEVEL}
      - F2B_DB_PURGE_AGE=${FAIL2BAN_DB_PURGE_AGE}
      - SSMTP_HOST=${SMTP_HOST}
      - SSMTP_PORT=${SMTP_PORT}
      - SSMTP_HOSTNAME=${SMTP_HOSTNAME}
      - SSMTP_USER=${SMTP_USER}
      - SSMTP_PASSWORD=${SMTP_PASSWORD}
      - SSMTP_TLS=${SMTP_TLS}
