goaccess:
    image: xavierh/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    restart: always
    volumes:
        - /docker/npm/nginx/logs:/opt/log
    ports:
        - '7880:7880'
    environment:
        - PUID=${MY_PUID}
        - PGID=${MY_PGID}
        - TZ=${TZ}        
        - SKIP_ARCHIVED_LOGS=False #optional 
